src/Entity/UserDetails.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 */
class UserDetails
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(
     *     min = 2,
     *     max = 100,
     *     minMessage = "Your first name must be at least {{ limit }} characters long",
     *     maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     * @ORM\Column(type="string", length=100)
     */
    private $first_name;

    /**
     * @Assert\Length(
     *     min = 2,
     *     max = 100,
     *     minMessage = "Your last name must be at least {{ limit }} characters long",
     *     maxMessage = "Your last name cannot be longer than {{ limit }} characters"
     * )
     * @ORM\Column(type="string", length=100)
     */
    private $last_name;

    /**
     * @Assert\Length(
     *     min = 5,
     *     max = 50,
     *     minMessage = "Your cell must be at least {{ limit }} characters long",
     *     maxMessage = "Your cell cannot be longer than {{ limit }} characters"
     * )
     * @ORM\Column(type="string", length=50)
     */
    private $cell;

    /**
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"image/jpg", "image/png"},
     *     mimeTypesMessage = "Please upload a valid PDF"
     * )
     * @ORM\OneToOne(targetEntity="File", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="file_id", referencedColumnName="id")
     */
    private $file;

    public function setFile(File $file)
    {
        $this->file = $file;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * @param mixed $first_name
     */
    public function setFirstName($first_name): void
    {
        $this->first_name = $first_name;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param mixed $last_name
     */
    public function setLastName($last_name): void
    {
        $this->last_name = $last_name;
    }

    /**
     * @return mixed
     */
    public function getCell()
    {
        return $this->cell;
    }

    /**
     * @param mixed $cell
     */
    public function setCell($cell): void
    {
        $this->cell = $cell;
    }


}

templates/landing/me/bills.html.twig
<div class="container-fluid">
    <section id="withdrawal-bg">
        <div class="container">
            <h3 class="title">
                My Bills
            </h3>
        </div>
    </section>
    <div class="row">

    </div>
</div>

templates/landing/me/login.html.twig
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg modal-center" role="document">
        <div class="modal-content login-content">
            <div class="modal-body row">
                <div class="col login-col">
                    <form action="{{ path('login') }}" method="post" id="formLogin">
                        <h1>Please, login. </h1>
                        <div class="form-group is-invalid" id="loginError">
                            Error
                        </div>
                        <div class="form-group input-field ">
                            <input type="email" name="_username" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group input-field ">
                            <input type="password" name="_password" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group row">
                            <div class="col">
                                <span class="btn btn-primary" id="login">Enter</span>
                                {#<button type="button" class="btn btn-primary" id="login">Enter</button>#}
                            </div>
                            {#<div class="col">#}
                                {#<a href="#" class="btn btn-link">forgot password</a>#}
                            {#</div>#}
                        </div>
                    </form>
                </div>
                <div class="col login-col">
                    <h1>
                        Not yet registered</h1>
                    <div>
                        Registration in our system will take you no more than 5 minutes
                    </div>
                    <div>
                        <a href="{{ path("register") }}">
                            <button type="button" class="btn btn-success">Registration</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/landing/me/profile.html.twig
<div class="container-fluid">
    <section id="profile-bg">
        <div class="container">
            <h3 class="title">
                Profile Page
            </h3>
        </div>
    </section>
    <div class="row">
        <div class="col-4">
            <h4 class="informative">First Name</h4>
            <label>{{ user.details.firstName }}</label>
            <div class="elementor-divider">
                <div class="elementor-divider-separator"></div>
            </div>
        </div>
        <div class="col-4">
            <h4 class="informative">Last Name</h4>
            <label>{{ user.details.lastName }}</label>
            <div class="elementor-divider">
                <div class="elementor-divider-separator"></div>
            </div>
        </div>
        <div class="col-4">
            <h4 class="informative">Email</h4>
            <label>{{ user.email }}</label>
            <div class="elementor-divider">
                <div class="elementor-divider-separator"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h4 class="informative">Signed up</h4>
            <label>{{ user.created|date("F j Y, H:i") }}</label>
            <div class="elementor-divider">
                <div class="elementor-divider-separator"></div>
            </div>
        </div>
        <div class="col-4">
            <h4 class="informative">Cell</h4>
            <label>{{ user.details.cell }}</label>
            <div class="elementor-divider">
                <div class="elementor-divider-separator"></div>
            </div>
        </div>
    </div>
</div>

templates/landing/me/refill.html.twig
<div class="container-fluid">
    <section id="withdrawal-bg">
        <div class="container">
            <h3 class="title">
                Refill
            </h3>
        </div>
    </section>
    <div class="row card-deck">
        <div class="col-4 card">
            <div class="card-body">
                <h4 class="card-title">Credit Card</h4>
                <form id="subscription-form">
                    <div id="card" class="card-js form-group" data-stripe="true"></div>
                    <div class="text-center">
                        <button type="button" class="btn btn-login">Add Payment Details</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8">
            <h4 class="informative">WHAT IS BITCOIN</h4>
            <h2 class="title">New Currency - New Lifestyle!</h2>
            <div class="elementor-divider left slice">
                <div class="elementor-divider-separator left"></div>
            </div>
            <p class="titled">
                Bitcoin is a revolutionary invention of the last decade. Its essential meaning is money
                digitization. It became the first decentralized peer-to-peer payment network for using without any
                central authority or middlemen. In a nutshell, bitcoin is the money for Internet. Its original
                purpose is providing all people with universal currency for different operations. Bitcoin can also
                be described as the most prominent triple entry bookkeeping system in existence.
            </p>
        </div>
    </div>
</div>

templates/landing/me/withdrawal.html.twig
<div class="container-fluid">
    <section id="withdrawal-bg">
        <div class="container">
            <h3 class="title">
                Withdrawals
            </h3>
        </div>
    </section>
    <div class="row card-deck">
        <div class="col-4 card">
            <div class="card-body">
                <h4 class="card-title">Credit Card</h4>
                <form id="subscription-form">
                    <div id="card" class="card-js form-group" data-stripe="true"></div>
                    <div class="text-center">
                        <button type="button" class="btn btn-login">Add Payment Details</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8">
            <h4 class="informative">WHAT IS BITCOIN</h4>
            <h2 class="title">New Currency - New Lifestyle!</h2>
            <div class="elementor-divider left slice">
                <div class="elementor-divider-separator left"></div>
            </div>
            <p class="titled">
                Bitcoin is a revolutionary invention of the last decade. Its essential meaning is money
                digitization. It became the first decentralized peer-to-peer payment network for using without any
                central authority or middlemen. In a nutshell, bitcoin is the money for Internet. Its original
                purpose is providing all people with universal currency for different operations. Bitcoin can also
                be described as the most prominent triple entry bookkeeping system in existence.
            </p>
        </div>
    </div>
</div>